### ISSUE TITLE
Something is broken in the last commit

### ISSUE THREAD

**Issue by fmaussion** [retostauffer/python-colorspace#6]
See https://github.com/OGGM/oggm/issues/1261 

I can reproduce in https://travis-ci.com/github/OGGM/r2d 

I have no clue why it worked for so long and suddenly not, maybe a dependency changed something. If you know what this is - excellent. Otherwise I can try to investigate.

**Comment by zeileis** [comment]
Fabien @fmaussion, I just started going through the issues of the package here on GitHub, sorry for not doing so earlier. I think/hope that this specific issue is outdated now. Finally there is also a release of the package on PyPI: <https://pypi.org/project/colorspace/>. So I'm closing this issue here. If you still have this problem or something related, it would be great if you would re-open the issue or open a new one. Thanks!
